# Generated by Django 3.1.4 on 2020-12-15 06:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('fecha_inicial', models.DateTimeField(blank=True, null=True)),
                ('fecha_final', models.DateTimeField(blank=True, null=True)),
                ('tipo', models.CharField(choices=[('1', 'Consulta de UDIS'), ('2', 'Consulta de TIIE')], default='1', max_length=1)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
