# Generated by Django 3.1.4 on 2020-12-15 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consulta_cedis', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consulta',
            name='fecha_final',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='consulta',
            name='fecha_inicial',
            field=models.DateField(blank=True, null=True),
        ),
    ]
